# Generated by Django 4.2.30 on 2026-06-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('CONCERT', 'Concert'), ('ONE_MAN_SHOW', 'One Man Show'), ('MARATHON', 'Marathon'), ('SPORT', 'Tournoi sportif'), ('CHARITY', 'Charité'), ('LEISURE', 'Sortie détente'), ('CULINARY', 'Festival culinaire')], default='CONCERT', max_length=20, verbose_name='Catégorie'),
        ),
    ]
