# Generated by Django 4.2.30 on 2026-06-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('CONCERT', 'Concert'), ('ONE_MAN_SHOW', 'One Man Show'), ('MARATHON', 'Marathon'), ('SPORT', 'Tournoi sportif'), ('CHARITY', 'Charité'), ('LEISURE', 'Sortie détente'), ('CULINARY', 'Festival culinaire'), ('RELIGIOUS', 'Religieux'), ('TOURISM', 'Tourisme'), ('FESTIVITY', 'Fêtes')], default='CONCERT', max_length=20, verbose_name='Catégorie'),
        ),
    ]
