# Generated by Django 4.2.30 on 2026-06-29 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('quota', models.PositiveIntegerField(verbose_name='Quota total disponible')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='Nombre vendus')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event', verbose_name='Événement')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Code unique')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée')], default='CONFIRMED', max_length=20, verbose_name='Statut réservation')),
                ('payment_status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé')], default='PAID', max_length=20, verbose_name='Statut paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tickets.tickettype', verbose_name='Type de billet')),
            ],
        ),
    ]
