# Generated by Django 4.2.30 on 2026-07-01 01:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE', 'Orange Money'), ('MTN', 'MTN MoMo'), ('MOOV', 'Moov Money (Flooz)'), ('CARD', 'Carte bancaire')], max_length=20, verbose_name='Moyen de paiement')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Référence transaction')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Paiement réussi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='tickets.reservation', verbose_name='Réservation')),
            ],
        ),
    ]
